services:
  - docker

language: node_js
dist: trusty
os: linux

before_install:
  - docker build -t cberd1509/ngfibonacci -f ./NGFibonacci/Dockerfile.dev ./NGFibonacci

script:
  #- export CHROME_BIN=/usr/bin/google-chrome
  - docker run cberd1509/ngfibonacci npm run test

after_success:
  - docker build -t $DOCKER_USER/multi-ngfibonacci ./NGFibonacci
  - docker build -t $DOCKER_USER/multi-nginx ./nginx
  - docker build -t $DOCKER_USER/multi-server ./Server
  - docker build -t $DOCKER_USER/multi-worker ./RedisWorker
  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
  #Image Pushing
  - docker push $DOCKER_USER/multi-ngfibonacci
  - docker push $DOCKER_USER/multi-nginx
  - docker push $DOCKER_USER/multi-server
  - docker push $DOCKER_USER/multi-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-532928905538
  bucket_path: docker-multi
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
