services:
  - docker

language: node_js
dist: trusty
os: linux

before_install:
  - docker build -t cberd1509/ngfibonacci -f ./NGFibonacci/Dockerfile.dev ./NGFibonacci

script:
  #- export CHROME_BIN=/usr/bin/google-chrome
  - docker run cberd1509/ngfibonacci npm run test

after_success:
  - docker build -t $DOCKER_USER/multi-ngfibonacci ./NGFibonacci
  - docker build -t $DOCKER_USER/multi-nginx ./nginx
  - docker build -t $DOCKER_USER/multi-server ./Server
  - docker build -t $DOCKER_USER/multi-worker ./RedisWorker
  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
  #Image Pushing
  - docker push $DOCKER_USER/multi-ngfibonacci
  - docker push $DOCKER_USER/multi-nginx
  - docker push $DOCKER_USER/multi-server
  - docker push $DOCKER_USER/multi-worker