version: '3'
services: 

  postgres:
    image: 'postgres:latest'
    env_file: .env

  redis:
    image: 'redis:latest'
  
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./Server
    volumes: 
      - /app/node_modules
      - ./Server:/app
    env_file: .env
    ports: 
      - 3004:3000
  
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./NGFibonacci
    volumes: 
      - /app/node_modules
      - ./NGFibonacci:/app

  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./RedisWorker
    env_file: .env
    volumes: 
      - /app/node_modules
      - ./RedisWorker:/app

  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3005:80'



  