FROM ubuntu

RUN apt-get update
RUN apt-get install -y curl wget gnupg2 gnupg1 gnupg

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list
RUN apt-get update && apt-get install --no-install-recommends -y google-chrome-stable

RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash -
RUN apt-get -y install nodejs

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY ./ ./

CMD ["npm","start"]
